const Types = {
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
    SET_PRODUCTS: "SET_PRODUCTS",
    ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
    REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
    SET_AMOUNT_FOR_PRODUCT_IN_CART: "SET_AMOUNT_FOR_PRODUCT_IN_CART",
    SET_PAGE: "SET_PAGE",
};

export default Types;